// <auto-generated />
using HateApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HateApi.Migrations
{
    [DbContext(typeof(HateContext))]
    [Migration("20200127194121_added-seeding")]
    partial class addedseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HateApi.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HateReward")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceReward")
                        .HasColumnType("int");

                    b.Property<string>("RewardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitUpgrade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RewardId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            RewardId = 1,
                            Description = "Do PILLAGE action on 5 huts",
                            HateReward = 0,
                            Name = "Pillaged",
                            ResourceReward = 3,
                            RewardType = "Attacker"
                        },
                        new
                        {
                            RewardId = 2,
                            Description = "Allow less than 5 PILLAGE actions",
                            HateReward = 0,
                            Name = "Hold the line",
                            ResourceReward = 4,
                            RewardType = "Defender"
                        },
                        new
                        {
                            RewardId = 3,
                            Description = "Do something else unrelated to the others",
                            HateReward = 4,
                            Name = "Something else",
                            ResourceReward = 0,
                            RewardType = "Both",
                            UnitUpgrade = "SomeCoolActionName"
                        });
                });

            modelBuilder.Entity("HateApi.Models.Scenario", b =>
                {
                    b.Property<int>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScenarioId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            ScenarioId = 1,
                            Description = "Go pillage a bunch of stuff!!",
                            Name = "Pillage the Village"
                        },
                        new
                        {
                            ScenarioId = 2,
                            Description = "Some other scenario description!!",
                            Name = "Some other scenario name"
                        });
                });

            modelBuilder.Entity("HateApi.Models.ScenarioRewardAssignment", b =>
                {
                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioRewardAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("RewardId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioRewardAssignments");

                    b.HasData(
                        new
                        {
                            RewardId = 1,
                            ScenarioId = 1,
                            ScenarioRewardAssignmentId = 1
                        },
                        new
                        {
                            RewardId = 2,
                            ScenarioId = 1,
                            ScenarioRewardAssignmentId = 2
                        },
                        new
                        {
                            RewardId = 3,
                            ScenarioId = 1,
                            ScenarioRewardAssignmentId = 3
                        });
                });

            modelBuilder.Entity("HateApi.Models.ScenarioSpecialAssignment", b =>
                {
                    b.Property<int>("SpecialId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioSpecialAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("SpecialId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioSpecialAssignments");

                    b.HasData(
                        new
                        {
                            SpecialId = 1,
                            ScenarioId = 1,
                            ScenarioSpecialAssignmentId = 1
                        },
                        new
                        {
                            SpecialId = 2,
                            ScenarioId = 1,
                            ScenarioSpecialAssignmentId = 2
                        });
                });

            modelBuilder.Entity("HateApi.Models.Special", b =>
                {
                    b.Property<int>("SpecialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecialId");

                    b.ToTable("Specials");

                    b.HasData(
                        new
                        {
                            SpecialId = 1,
                            Description = "Make sure to be sitting down while playing.",
                            Name = "Special Chair"
                        },
                        new
                        {
                            SpecialId = 2,
                            Description = "Play with your eyes closed.",
                            Name = "Special Action"
                        });
                });

            modelBuilder.Entity("HateApi.Models.ScenarioRewardAssignment", b =>
                {
                    b.HasOne("HateApi.Models.Reward", "Reward")
                        .WithMany("ScenarioRewardAssignments")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HateApi.Models.Scenario", "Scenario")
                        .WithMany("ScenarioRewardAssignments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HateApi.Models.ScenarioSpecialAssignment", b =>
                {
                    b.HasOne("HateApi.Models.Scenario", "Scenario")
                        .WithMany("ScenarioSpecialAssignments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HateApi.Models.Special", "Special")
                        .WithMany("ScenarioSpecialAssignments")
                        .HasForeignKey("SpecialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
